/* Generated by scripts/generate-config.js. Do not edit manually. */
window.SUPABASE_URL = "https://nyditfrfzarntmekcyli.supabase.co";
window.SUPABASE_ANON_KEY = "sb_publishable_aI5Lt5-xOyOYyeDWj441EA_30hg283Y";
