/* Generated by scripts/generate-config.js. Do not edit manually. */
window.SUPABASE_URL = "https://nyditfrfzarntmekcyli.supabase.co";
window.SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55ZGl0ZnJmemFybnRtZWtjeWxpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODcxNzk2ODYsImV4cCI6MjEwMjc1NTY4Nn0.VckFNUDhBAvHrPDwwoZ15chcdrMyPAiG03IDkBUQFa8";
