const fs = require("fs");
const path = require("path");

function loadDotEnv() {
  const envPath = path.resolve(__dirname, "..", ".env");
  if (!fs.existsSync(envPath)) return;

  for (const line of fs.readFileSync(envPath, "utf8").split(/\r?\n/)) {
    const match = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/);
    if (match && !process.env[match[1]]) {
      process.env[match[1]] = match[2].replace(/^['"]|['"]$/g, "");
    }
  }
}

loadDotEnv();

const url = process.env.SUPABASE_URL || "";
const anonKey = process.env.SUPABASE_ANON_KEY || process.env.SUPABASE_PUBLISHABLE_KEY || "";

if (!url || !anonKey) {
  throw new Error(
    "Missing Supabase configuration. Set SUPABASE_URL and either SUPABASE_ANON_KEY or SUPABASE_PUBLISHABLE_KEY in .env or the deployment environment."
  );
}

const output = `/* Generated by scripts/generate-config.js. Do not edit manually. */\nwindow.SUPABASE_URL = ${JSON.stringify(url)};\nwindow.SUPABASE_ANON_KEY = ${JSON.stringify(anonKey)};\nwindow.SUPABASE_PUBLISHABLE_KEY = window.SUPABASE_ANON_KEY;\n`;
fs.writeFileSync(path.resolve(__dirname, "..", "js", "supabase-config.js"), output);